# Start with a base image containing Java runtime and Maven
FROM maven:3.8.4-openjdk-17 as build

# Copy the project files into the container
COPY src /hoanggiang/src
COPY pom.xml /hoanggiang

# Set the working directory
WORKDIR /hoanggiang

# Build the application as a WAR file and skip tests
RUN mvn clean package -DskipTests

FROM openjdk:17-slim

# Copy WAR file to the webapps directory in Tomcat
# Ensure that the path to the WAR file matches the actual file name generated by Maven
COPY --from=build /hoanggiang/target/*.war /hoanggiang/app.war

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/hoanggiang/app.war"]

